"""2st migrations

Revision ID: 0af107c949a8
Revises: c976d4004dfd
Create Date: 2025-04-05 11:52:14.459957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0af107c949a8'
down_revision: Union[str, None] = 'c976d4004dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=True)
    op.create_index(op.f('ix_employees_uid'), 'employees', ['uid'], unique=True)
    op.create_table('employee_info',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_uid', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_uid'], ['employees.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employee_info_phone_number'), 'employee_info', ['phone_number'], unique=True)
    op.create_index(op.f('ix_employee_info_uid'), 'employee_info', ['uid'], unique=True)
    op.create_table('item_transactions',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_time', sa.Time(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employee_uid', sa.Uuid(), nullable=True),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('item_uid', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_uid'], ['employees.uid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_uid'], ['items.uid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_item_transactions_action_type'), 'item_transactions', ['action_type'], unique=False)
    op.create_index(op.f('ix_item_transactions_transaction_date'), 'item_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_item_transactions_transaction_time'), 'item_transactions', ['transaction_time'], unique=False)
    op.create_index(op.f('ix_item_transactions_uid'), 'item_transactions', ['uid'], unique=True)
    op.add_column('purchase', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_purchase_category'), 'purchase', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_category'), table_name='purchase')
    op.drop_column('purchase', 'category')
    op.drop_index(op.f('ix_item_transactions_uid'), table_name='item_transactions')
    op.drop_index(op.f('ix_item_transactions_transaction_time'), table_name='item_transactions')
    op.drop_index(op.f('ix_item_transactions_transaction_date'), table_name='item_transactions')
    op.drop_index(op.f('ix_item_transactions_action_type'), table_name='item_transactions')
    op.drop_table('item_transactions')
    op.drop_index(op.f('ix_employee_info_uid'), table_name='employee_info')
    op.drop_index(op.f('ix_employee_info_phone_number'), table_name='employee_info')
    op.drop_table('employee_info')
    op.drop_index(op.f('ix_employees_uid'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
