"""3st migrations

Revision ID: 8f761e9a5a00
Revises: c3cc8c9294fd
Create Date: 2025-04-28 15:17:33.489335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f761e9a5a00'
down_revision: Union[str, None] = 'c3cc8c9294fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_info', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee_info', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_info', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_info', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
